# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestforsto',
            name='order_id',
        ),
    ]
