# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0002_remove_requestforsto_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforsto',
            name='res_response',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
