# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqs', '0003_requestforsto_res_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestforsto',
            name='car_model',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requestforsto',
            name='client_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='requestforsto',
            name='description',
            field=models.TextField(),
        ),
    ]
